"""Exceptions generated by the various services."""


# Exception if creating a base class that should not be instantiated
class AbstractClassError(Exception):
    """Raised when an abstract class is instantiated."""
