version: "3"
services:
  localstack:
    image: localstack/localstack:3.3
    container_name: localstack
    environment:
      - SERVICES=sqs,s3
      - DEBUG=1
    ports:
      - "4566:4566"
      - "4571:4571"
    networks:
      - foresight_network

  timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: timescaledb
    environment:
      POSTGRES_DB: project_foresight
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - foresight_network
    volumes:
      - timescaledb_data:/var/lib/postgresql/data

networks:
  foresight_network:
    driver: bridge

volumes:
  timescaledb_data:
