# Pre-commit Checks
## Theoretically should not ever fail if the pre-commit checks are passing locally
name: Pre-commit Checks

on: [push, pull_request]

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.x

    - name: Install pre-commit
      run: pip install pre-commit

    - name: Run pre-commit checks
      run: pre-commit run --all-files
